In [7]:
!pip install bs4

Requirement already satisfied: bs4 in /usr/local/lib/python3.12/dist-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.15.0)

In [8]:
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm  #for better presentation of pages progress
import pandas as pd

In [9]:
req=requests.get('https://quotes.toscrape.com/')

In [10]:
soup = BeautifulSoup(req.text,'html.parser')

In [11]:
#all the quotes one after the other

#storing all the data into a list
data = []
for sp in soup.find_all('div',class_='quote'):
  #print(sp)
  quote = sp.find('span',class_ = 'text').text[1:-1]
  author = sp.find('small',class_='author').text
  author_id = sp.find('a').get('href')

  tags = []
  for tag in sp.find_all('a',class_='tag') :
    tags.append(tag.text)

  tags = ','.join(tags) #to be seperated by commas in a line
  data.append([quote,author,author_id,tags])
  print(quote)
  print(author)
  print(author_id)
  print(tags)
  print()
  print("--"*20)
  print()

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.
Albert Einstein
/author/Albert-Einstein
change,deep-thoughts,thinking,world

----------------------------------------

It is our choices, Harry, that show what we truly are, far more than our abilities.
J.K. Rowling
/author/J-K-Rowling
abilities,choices

----------------------------------------

There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.
Albert Einstein
/author/Albert-Einstein
inspirational,life,live,miracle,miracles

----------------------------------------

The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.
Jane Austen
/author/Jane-Austen
aliteracy,books,classic,humor

----------------------------------------

Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.
Marilyn Monroe
/author/Marilyn-Monroe
be-yourself,inspirational

----------------------------------------

Try not to become a man of success. Rather become a man of value.
Albert Einstein
/author/Albert-Einstein
adulthood,success,value

----------------------------------------

It is better to be hated for what you are than to be loved for what you are not.
André Gide
/author/Andre-Gide
life,love

----------------------------------------

I have not failed. I've just found 10,000 ways that won't work.
Thomas A. Edison
/author/Thomas-A-Edison
edison,failure,inspirational,paraphrased

----------------------------------------

A woman is like a tea bag; you never know how strong it is until it's in hot water.
Eleanor Roosevelt
/author/Eleanor-Roosevelt
misattributed-eleanor-roosevelt

----------------------------------------

A day without sunshine is like, you know, night.
Steve Martin
/author/Steve-Martin
humor,obvious,simile

----------------------------------------

In [12]:
#creating page links
for page in range(2,11):
  print('https://quotes.toscrape.com/page/'+str(page))

https://quotes.toscrape.com/page/2
https://quotes.toscrape.com/page/3
https://quotes.toscrape.com/page/4
https://quotes.toscrape.com/page/5
https://quotes.toscrape.com/page/6
https://quotes.toscrape.com/page/7
https://quotes.toscrape.com/page/8
https://quotes.toscrape.com/page/9
https://quotes.toscrape.com/page/10

In [13]:
for page in range(2,11):
  link = 'https://quotes.toscrape.com/page/'+str(page)
  response = requests.get(link)
  soup = BeautifulSoup(response.text, 'html.parser')  # soup is prepared of multiple page

In [14]:
len(response.text)

9901

#### once the Soup is prepared for multiple pages we can use the similar approch of single page for extracting contents of everypage

In [15]:
data = []
for page in tqdm(range(1,11)):
  link = 'https://quotes.toscrape.com/page/'+str(page)
  response = requests.get(link)
  soup = BeautifulSoup(response.text, 'html.parser')  # soup is prepared of multiple pages

  #build the same logic to single webpage scrapper for soup

  for sp in soup.find_all('div',class_='quote'):
  #print(sp)
    quote = sp.find('span',class_ = 'text').text[1:-1]
    author = sp.find('small',class_='author').text
    author_id = sp.find('a').get('href')

    tags = []
    for tag in sp.find_all('a',class_='tag') :
      tags.append(tag.text)

    tags = ','.join(tags) #to be seperated by commas in a line
    data.append([quote,author,author_id,tags])
    print(quote)
    print(author)
    print(author_id)
    print(tags)
    print()
    print("--"*20)
    print()

 10%|█         | 1/10 [00:00<00:08,  1.03it/s]

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.
Albert Einstein
/author/Albert-Einstein
change,deep-thoughts,thinking,world

----------------------------------------

It is our choices, Harry, that show what we truly are, far more than our abilities.
J.K. Rowling
/author/J-K-Rowling
abilities,choices

----------------------------------------

There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.
Albert Einstein
/author/Albert-Einstein
inspirational,life,live,miracle,miracles

----------------------------------------

The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.
Jane Austen
/author/Jane-Austen
aliteracy,books,classic,humor

----------------------------------------

Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.
Marilyn Monroe
/author/Marilyn-Monroe
be-yourself,inspirational

----------------------------------------

Try not to become a man of success. Rather become a man of value.
Albert Einstein
/author/Albert-Einstein
adulthood,success,value

----------------------------------------

It is better to be hated for what you are than to be loved for what you are not.
André Gide
/author/Andre-Gide
life,love

----------------------------------------

I have not failed. I've just found 10,000 ways that won't work.
Thomas A. Edison
/author/Thomas-A-Edison
edison,failure,inspirational,paraphrased

----------------------------------------

A woman is like a tea bag; you never know how strong it is until it's in hot water.
Eleanor Roosevelt
/author/Eleanor-Roosevelt
misattributed-eleanor-roosevelt

----------------------------------------

A day without sunshine is like, you know, night.
Steve Martin
/author/Steve-Martin
humor,obvious,simile

----------------------------------------

 20%|██        | 2/10 [00:01<00:07,  1.04it/s]

This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.
Marilyn Monroe
/author/Marilyn-Monroe
friends,heartbreak,inspirational,life,love,sisters

----------------------------------------

It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.
J.K. Rowling
/author/J-K-Rowling
courage,friends

----------------------------------------

If you can't explain it to a six year old, you don't understand it yourself.
Albert Einstein
/author/Albert-Einstein
simplicity,understand

----------------------------------------

You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect—you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.
Bob Marley
/author/Bob-Marley
love

----------------------------------------

I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.
Dr. Seuss
/author/Dr-Seuss
fantasy

----------------------------------------

I may not have gone where I intended to go, but I think I have ended up where I needed to be.
Douglas Adams
/author/Douglas-Adams
life,navigation

----------------------------------------

The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.
Elie Wiesel
/author/Elie-Wiesel
activism,apathy,hate,indifference,inspirational,love,opposite,philosophy

----------------------------------------

It is not a lack of love, but a lack of friendship that makes unhappy marriages.
Friedrich Nietzsche
/author/Friedrich-Nietzsche
friendship,lack-of-friendship,lack-of-love,love,marriage,unhappy-marriage

----------------------------------------

Good friends, good books, and a sleepy conscience: this is the ideal life.
Mark Twain
/author/Mark-Twain
books,contentment,friends,friendship,life

----------------------------------------

Life is what happens to us while we are making other plans.
Allen Saunders
/author/Allen-Saunders
fate,life,misattributed-john-lennon,planning,plans

----------------------------------------

 30%|███       | 3/10 [00:02<00:06,  1.00it/s]

I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.
Pablo Neruda
/author/Pablo-Neruda
love,poetry

----------------------------------------

For every minute you are angry you lose sixty seconds of happiness.
Ralph Waldo Emerson
/author/Ralph-Waldo-Emerson
happiness

----------------------------------------

If you judge people, you have no time to love them.
Mother Teresa
/author/Mother-Teresa
attributed-no-source

----------------------------------------

Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.
Garrison Keillor
/author/Garrison-Keillor
humor,religion

----------------------------------------

Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.
Jim Henson
/author/Jim-Henson
humor

----------------------------------------

Today you are You, that is truer than true. There is no one alive who is Youer than You.
Dr. Seuss
/author/Dr-Seuss
comedy,life,yourself

----------------------------------------

If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.
Albert Einstein
/author/Albert-Einstein
children,fairy-tales

----------------------------------------

It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default.
J.K. Rowling
/author/J-K-Rowling


----------------------------------------

Logic will get you from A to Z; imagination will get you everywhere.
Albert Einstein
/author/Albert-Einstein
imagination

----------------------------------------

One good thing about music, when it hits you, you feel no pain.
Bob Marley
/author/Bob-Marley
music

----------------------------------------

 40%|████      | 4/10 [00:03<00:05,  1.02it/s]

The more that you read, the more things you will know. The more that you learn, the more places you'll go.
Dr. Seuss
/author/Dr-Seuss
learning,reading,seuss

----------------------------------------

Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?
J.K. Rowling
/author/J-K-Rowling
dumbledore

----------------------------------------

The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.
Bob Marley
/author/Bob-Marley
friendship

----------------------------------------

Not all of us can do great things. But we can do small things with great love.
Mother Teresa
/author/Mother-Teresa
misattributed-to-mother-teresa,paraphrased

----------------------------------------

To the well-organized mind, death is but the next great adventure.
J.K. Rowling
/author/J-K-Rowling
death,inspirational

----------------------------------------

All you need is love. But a little chocolate now and then doesn't hurt.
Charles M. Schulz
/author/Charles-M-Schulz
chocolate,food,humor

----------------------------------------

We read to know we're not alone.
William Nicholson
/author/William-Nicholson
misattributed-to-c-s-lewis,reading

----------------------------------------

Any fool can know. The point is to understand.
Albert Einstein
/author/Albert-Einstein
knowledge,learning,understanding,wisdom

----------------------------------------

I have always imagined that Paradise will be a kind of library.
Jorge Luis Borges
/author/Jorge-Luis-Borges
books,library

----------------------------------------

It is never too late to be what you might have been.
George Eliot
/author/George-Eliot
inspirational

----------------------------------------

 50%|█████     | 5/10 [00:04<00:04,  1.02it/s]

A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.
George R.R. Martin
/author/George-R-R-Martin
read,readers,reading,reading-books

----------------------------------------

You can never get a cup of tea large enough or a book long enough to suit me.
C.S. Lewis
/author/C-S-Lewis
books,inspirational,reading,tea

----------------------------------------

You believe lies so you eventually learn to trust no one but yourself.
Marilyn Monroe
/author/Marilyn-Monroe


----------------------------------------

If you can make a woman laugh, you can make her do anything.
Marilyn Monroe
/author/Marilyn-Monroe
girls,love

----------------------------------------

Life is like riding a bicycle. To keep your balance, you must keep moving.
Albert Einstein
/author/Albert-Einstein
life,simile

----------------------------------------

The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.
Marilyn Monroe
/author/Marilyn-Monroe
love

----------------------------------------

A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left.
Marilyn Monroe
/author/Marilyn-Monroe
attributed-no-source

----------------------------------------

Only in the darkness can you see the stars.
Martin Luther King Jr.
/author/Martin-Luther-King-Jr
hope,inspirational

----------------------------------------

It matters not what someone is born, but what they grow to be.
J.K. Rowling
/author/J-K-Rowling
dumbledore

----------------------------------------

Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.
James Baldwin
/author/James-Baldwin
love

----------------------------------------

 60%|██████    | 6/10 [00:05<00:03,  1.03it/s]

There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.
Jane Austen
/author/Jane-Austen
friendship,love

----------------------------------------

Do one thing every day that scares you.
Eleanor Roosevelt
/author/Eleanor-Roosevelt
attributed,fear,inspiration

----------------------------------------

I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.
Marilyn Monroe
/author/Marilyn-Monroe
attributed-no-source

----------------------------------------

If I were not a physicist, I would probably be a musician. I often think in music. I live my daydreams in music. I see my life in terms of music.
Albert Einstein
/author/Albert-Einstein
music

----------------------------------------

If you only read the books that everyone else is reading, you can only think what everyone else is thinking.
Haruki Murakami
/author/Haruki-Murakami
books,thought

----------------------------------------

The difference between genius and stupidity is: genius has its limits.
Alexandre Dumas fils
/author/Alexandre-Dumas-fils
misattributed-to-einstein

----------------------------------------

He's like a drug for you, Bella.
Stephenie Meyer
/author/Stephenie-Meyer
drug,romance,simile

----------------------------------------

There is no friend as loyal as a book.
Ernest Hemingway
/author/Ernest-Hemingway
books,friends,novelist-quotes

----------------------------------------

When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.
Helen Keller
/author/Helen-Keller
inspirational

----------------------------------------

Life isn't about finding yourself. Life is about creating yourself.
George Bernard Shaw
/author/George-Bernard-Shaw
inspirational,life,yourself

----------------------------------------

 70%|███████   | 7/10 [00:06<00:02,  1.03it/s]

That's the problem with drinking, I thought, as I poured myself a drink. If something bad happens you drink in an attempt to forget; if something good happens you drink in order to celebrate; and if nothing happens you drink to make something happen.
Charles Bukowski
/author/Charles-Bukowski
alcohol

----------------------------------------

You don’t forget the face of the person who was your last hope.
Suzanne Collins
/author/Suzanne-Collins
the-hunger-games

----------------------------------------

Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.
Suzanne Collins
/author/Suzanne-Collins
humor

----------------------------------------

To love at all is to be vulnerable. Love anything and your heart will be wrung and possibly broken. If you want to make sure of keeping it intact you must give it to no one, not even an animal. Wrap it carefully round with hobbies and little luxuries; avoid all entanglements. Lock it up safe in the casket or coffin of your selfishness. But in that casket, safe, dark, motionless, airless, it will change. It will not be broken; it will become unbreakable, impenetrable, irredeemable. To love is to be vulnerable.
C.S. Lewis
/author/C-S-Lewis
love

----------------------------------------

Not all those who wander are lost.
J.R.R. Tolkien
/author/J-R-R-Tolkien
bilbo,journey,lost,quest,travel,wander

----------------------------------------

Do not pity the dead, Harry. Pity the living, and, above all those who live without love.
J.K. Rowling
/author/J-K-Rowling
live-death-love

----------------------------------------

There is nothing to writing. All you do is sit down at a typewriter and bleed.
Ernest Hemingway
/author/Ernest-Hemingway
good,writing

----------------------------------------

Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.
Ralph Waldo Emerson
/author/Ralph-Waldo-Emerson
life,regrets

----------------------------------------

I have never let my schooling interfere with my education.
Mark Twain
/author/Mark-Twain
education

----------------------------------------

I have heard there are troubles of more than one kind. Some come from ahead and some come from behind. But I've bought a big bat. I'm all ready you see. Now my troubles are going to have troubles with me!
Dr. Seuss
/author/Dr-Seuss
troubles

----------------------------------------

 80%|████████  | 8/10 [00:07<00:01,  1.02it/s]

If I had a flower for every time I thought of you...I could walk through my garden forever.
Alfred Tennyson
/author/Alfred-Tennyson
friendship,love

----------------------------------------

Some people never go crazy. What truly horrible lives they must lead.
Charles Bukowski
/author/Charles-Bukowski
humor

----------------------------------------

The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.
Terry Pratchett
/author/Terry-Pratchett
humor,open-mind,thinking

----------------------------------------

Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!
Dr. Seuss
/author/Dr-Seuss
humor,philosophy

----------------------------------------

What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though.
J.D. Salinger
/author/J-D-Salinger
authors,books,literature,reading,writing

----------------------------------------

The reason I talk to myself is because I’m the only one whose answers I accept.
George Carlin
/author/George-Carlin
humor,insanity,lies,lying,self-indulgence,truth

----------------------------------------

You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.
John Lennon
/author/John-Lennon
beatles,connection,dreamers,dreaming,dreams,hope,inspirational,peace

----------------------------------------

I am free of all prejudice. I hate everyone equally.
W.C. Fields
/author/W-C-Fields
humor,sinister

----------------------------------------

The question isn't who is going to let me; it's who is going to stop me.
Ayn Rand
/author/Ayn-Rand


----------------------------------------

′Classic′ - a book which people praise and don't read.
Mark Twain
/author/Mark-Twain
books,classic,reading

----------------------------------------

 90%|█████████ | 9/10 [00:08<00:00,  1.03it/s]

Anyone who has never made a mistake has never tried anything new.
Albert Einstein
/author/Albert-Einstein
mistakes

----------------------------------------

A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.
Jane Austen
/author/Jane-Austen
humor,love,romantic,women

----------------------------------------

Remember, if the time should come when you have to make a choice between what is right and what is easy, remember what happened to a boy who was good, and kind, and brave, because he strayed across the path of Lord Voldemort. Remember Cedric Diggory.
J.K. Rowling
/author/J-K-Rowling
integrity

----------------------------------------

I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library.
Jane Austen
/author/Jane-Austen
books,library,reading

----------------------------------------

There are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense.
Jane Austen
/author/Jane-Austen
elizabeth-bennet,jane-austen

----------------------------------------

Some day you will be old enough to start reading fairy tales again.
C.S. Lewis
/author/C-S-Lewis
age,fairytales,growing-up

----------------------------------------

We are not necessarily doubting that God will do the best for us; we are wondering how painful the best will turn out to be.
C.S. Lewis
/author/C-S-Lewis
god

----------------------------------------

The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.
Mark Twain
/author/Mark-Twain
death,life

----------------------------------------

A lie can travel half way around the world while the truth is putting on its shoes.
Mark Twain
/author/Mark-Twain
misattributed-mark-twain,truth

----------------------------------------

I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else.
C.S. Lewis
/author/C-S-Lewis
christianity,faith,religion,sun

----------------------------------------

100%|██████████| 10/10 [00:09<00:00,  1.03it/s]

The truth." Dumbledore sighed. "It is a beautiful and terrible thing, and should therefore be treated with great caution.
J.K. Rowling
/author/J-K-Rowling
truth

----------------------------------------

I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.
Jimi Hendrix
/author/Jimi-Hendrix
death,life

----------------------------------------

To die will be an awfully big adventure.
J.M. Barrie
/author/J-M-Barrie
adventure,love

----------------------------------------

It takes courage to grow up and become who you really are.
E.E. Cummings
/author/E-E-Cummings
courage

----------------------------------------

But better to get hurt by the truth than comforted with a lie.
Khaled Hosseini
/author/Khaled-Hosseini
life

----------------------------------------

You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.
Harper Lee
/author/Harper-Lee
better-life-empathy

----------------------------------------

You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children.
Madeleine L'Engle
/author/Madeleine-LEngle
books,children,difficult,grown-ups,write,writers,writing

----------------------------------------

Never tell the truth to people who are not worthy of it.
Mark Twain
/author/Mark-Twain
truth

----------------------------------------

A person's a person, no matter how small.
Dr. Seuss
/author/Dr-Seuss
inspirational

----------------------------------------

... a mind needs books as a sword needs a whetstone, if it is to keep its edge.
George R.R. Martin
/author/George-R-R-Martin
books,mind

----------------------------------------

In [16]:
len(data)

100

formating data into dataset or dataframe **formate**

In [17]:
df = pd.DataFrame(data, columns=['quote','author','author_id','tags'])

In [18]:
df

,quote,author,author_id,tags
0,The world as we have created it is a process o...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world"
1,"It is our choices, Harry, that show what we tr...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices"
2,There are only two ways to live your life. One...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles"
3,"The person, be it gentleman or lady, who has n...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor"
4,"Imperfection is beauty, madness is genius and ...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational"
...,...,...,...,...
95,You never really understand a person until you...,Harper Lee,/author/Harper-Lee,better-life-empathy
96,You have to write the book that wants to be wr...,Madeleine L'Engle,/author/Madeleine-LEngle,"books,children,difficult,grown-ups,write,write..."
97,Never tell the truth to people who are not wor...,Mark Twain,/author/Mark-Twain,truth
98,"A person's a person, no matter how small.",Dr. Seuss,/author/Dr-Seuss,inspirational
99,... a mind needs books as a sword needs a whet...,George R.R. Martin,/author/George-R-R-Martin,"books,mind"

adding prefix links to directly specify the links to browser

In [19]:
df['author_link']='https://quotes.toscrape.com'+df['author_id']

In [20]:
df

,quote,author,author_id,tags,author_link
0,The world as we have created it is a process o...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world",https://quotes.toscrape.com/author/Albert-Eins...
1,"It is our choices, Harry, that show what we tr...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices",https://quotes.toscrape.com/author/J-K-Rowling
2,There are only two ways to live your life. One...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles",https://quotes.toscrape.com/author/Albert-Eins...
3,"The person, be it gentleman or lady, who has n...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor",https://quotes.toscrape.com/author/Jane-Austen
4,"Imperfection is beauty, madness is genius and ...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational",https://quotes.toscrape.com/author/Marilyn-Monroe
...,...,...,...,...,...
95,You never really understand a person until you...,Harper Lee,/author/Harper-Lee,better-life-empathy,https://quotes.toscrape.com/author/Harper-Lee
96,You have to write the book that wants to be wr...,Madeleine L'Engle,/author/Madeleine-LEngle,"books,children,difficult,grown-ups,write,write...",https://quotes.toscrape.com/author/Madeleine-L...
97,Never tell the truth to people who are not wor...,Mark Twain,/author/Mark-Twain,truth,https://quotes.toscrape.com/author/Mark-Twain
98,"A person's a person, no matter how small.",Dr. Seuss,/author/Dr-Seuss,inspirational,https://quotes.toscrape.com/author/Dr-Seuss
99,... a mind needs books as a sword needs a whet...,George R.R. Martin,/author/George-R-R-Martin,"books,mind",https://quotes.toscrape.com/author/George-R-R-...

### ***saving*** scraped data into a  csv file

In [21]:
df.to_csv('quotes.csv',index = False)